### ISSUE TITLE
小问题：RSS输出的正文的标签是 `<summary>`

### ISSUE THREAD

**Issue by Pathsis** [la3rence/site#329]
<img width="507" alt="image" src="https://github.com/la3rence/site/assets/72077265/c2c9b645-27ea-4666-a611-b7dce79e5384">

wo我记得以前是 `<content>` ，不知道会不会有什么影响。

**Comment by la3rence** [comment]
大多数 RSS Reader 都不影响。

https://datatracker.ietf.org/doc/html/rfc4287

`summary` 或 `content` 都是作为 `entry`  的子节点都是可选参数。https://datatracker.ietf.org/doc/html/rfc4287#section-4.1.2

这里换成 content 也没问题，只要能经过格式校验就行。

 https://validator.w3.org/feed/

/label rss

**Comment by la3rence** [comment]
大多数流行 RSS 客户端容错性都很好，XML 结构上没有严重差错的话对于 Feed 能否订阅也无影响。如果订阅用户众多，建议还是先确保通过 w3 feed validator 校验，然后利用 CDN 或缓存。我自己这 Feed 放 CDN 上，看了一下日志，平均下来一分钟就会被某个客户端爬一次，大多数流量全在 RSS 上面，所以才有选择的减少了尺寸。

**Comment by Pathsis** [comment]
> 不影响。我自己使用过的 RSS 阅读器或者 FreshRSS 这类聚合平台都能正常解析。
> 
> `summary` 或 `content` 都是作为 `entry` 的子节点都是可选参数。https://datatracker.ietf.org/doc/html/rfc4287#section-4.1.2
> 
> 这里换成 content 也没问题，只要能通过格式校验就行，比如注意 `description` 不是 Atom Feed 的合法参数。
> 
> https://validator.w3.org/feed/
> 
> /label rss

多谢！我自己就设置了一个 description 参数。看来得改一下。

**Comment by Pathsis** [comment]
> 大多数流行 RSS 客户端容错性都很好，XML 结构上没有严重差错的话对于 Feed 能否订阅也无影响。如果订阅用户众多，建议还是先确保通过 w3 feed validator 校验，然后利用 CDN 或缓存。我自己这 Feed 放 CDN 上，看了一下日志，平均下来一分钟就会被某个客户端爬一次，大多数流量全在 RSS 上面，所以才有选择的减少了尺寸。

确实， Vercel 上流量最大的一块就是 feed 输出的数据。我现在也设置为 10 个输出条目了。
