### ISSUE TITLE
feed等结构化数据没有正确渲染

### ISSUE THREAD

**Issue by Pathsis** [la3rence/site#340]
我查看了您的网站的head的结构化数据，好像没有正确渲染。

<img width="501" alt="屏幕截图 2024-01-18 230049" src="https://github.com/la3rence/site/assets/72077265/ef46ae08-454e-41cd-84db-2f76e6ff0f01">

追随您的代码，我的也似乎没有正确渲染。

<img width="489" alt="屏幕截图 2024-01-18 230834" src="https://github.com/la3rence/site/assets/72077265/f2f41f04-3164-4994-9fe5-5695d19ed12d">

**Comment by la3rence** [comment]
https://search.google.com/test/rich-results/result?id=XobYniH-49AfeKZ9WviPqw

看上去没问题啊……

**Comment by Pathsis** [comment]
你的datePublished返回的值是null啊。

我的网站的发布和更新时间一直是2020-01-01。

使用的是你的如下代码：

```js
 const isoDate = date ? new Date(date).toISOString() : new Date("2020-01-01");
  const isoModifiedDate = modified ? new Date(modified).toISOString() : isoDate;
  const structuredData = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: title,
    datePublished: isoDate,
    dateModified: isoModifiedDate,
  });

...

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: structuredData }}
        />
        <link
          rel="alternate"
          type="application/atom+xml"
          title="siteTitle"
          href={config.feedPath}
        />
````

**Comment by la3rence** [comment]
时间不是必须的，只要通过搜索校验就可以了。我是特意去掉的，索引页没必要加这个。
